# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8ed9ce37acbebcef713e3742f374626c38ad0d236f610f8e4d9b530534f6546a221cb1cd53a0ba44e72cf330475d74db7c2d2d537c29c9f8e90195ff1a95edc

test:
  secret_key_base: 3d17ce833fb43fbe771e5a0416e4643ef8bef08c1709094afabc11dc37d1118db1f784b91f42d0c3bdbaab7490a83b1a4ff777394777815db9107b176304f02b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
